# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern: ^/admin/
            anonymous: true
            provider: fos_userbundle
            form_login:
                login_path: admin_fos_user_security_login
                check_path: admin_fos_user_security_check
                default_target_path: admin_admin_index
            logout:
                path: admin_fos_user_security_logout
                target: admin_fos_user_security_login
            remember_me:
                secret: '%secret%'
            context: application

        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            form_login:
                use_referer: true
                login_path: front_fos_user_security_login
                check_path: front_fos_user_security_check

                default_target_path: front_front_home_index
            logout:
                path: front_fos_user_security_logout
                target: front_fos_user_security_login
            remember_me:
                secret: '%secret%'
            context: application

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }