front_fos_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }

front_fos_user_security_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

front_fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }


#